# Generated by Django 6.0.5 on 2026-05-26 14:15

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('factor_kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=19)),
                ('unit', models.CharField(max_length=50)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=50)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('source_row_number', models.IntegerField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('activity_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity_original', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit_original', models.CharField(max_length=50)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit_normalized', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('vendor_or_provider', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('upload_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.uploadbatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalActivityRecord',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('source_type', models.CharField(max_length=50)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('source_row_number', models.IntegerField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('activity_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity_original', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit_original', models.CharField(max_length=50)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit_normalized', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('vendor_or_provider', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('upload_batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingestion.uploadbatch')),
            ],
            options={
                'verbose_name': 'historical activity record',
                'verbose_name_plural': 'historical activity records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
